# Model-Konfiguration für deine Struktur
models:
  base_path: "X:/pypygennew/models"
  auto_scan: true
  
  # Definiere deine verfügbaren Modelle explizit
  image_models:
    realistic_vision:
      path: "X:/pypygennew/models/image/Realistic_Vision_V6.0_B1_noVAE"
      type: "txt2img"
      default: true  # Als Standard-Modell setzen
      
    sdxl_base:
      path: "X:/pypygennew/models/image/stable-diffusion-xl-base-1.0"
      type: "txt2img"
      
    sdxl_refiner:
      path: "X:/pypygennew/models/image/stable-diffusion-xl-refiner-1.0" 
      type: "refiner"
      
  video_models:
    animatediff:
      path: "X:/pypygennew/models/video/animatediff"
      type: "txt2vid"
      
    svd_img2vid:
      path: "X:/pypygennew/models/video/stable-video-diffusion-img2vid"
      type: "img2vid"
      default: true
      
    svd_img2vid_xt:
      path: "X:/pypygennew/models/video/stable-video-diffusion-img2vid-xt"
      type: "img2vid"

# Server-Konfiguration
server:
  host: "127.0.0.1"
  port: 3000
  debug: true

# Performance-Optimierung 
performance:
  prefer_gpu: true
  enable_xformers: true
  low_vram_mode: false  # Du hast genug VRAM mit den Modellen